name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build


    - name: Build debug app
      run: ./gradlew assembleDebug
    - name: Check directory
      run: ls

    - name: Upload artifacts
      uses: actions/download-artifact@v3.0.1
      with:
          name: app-debug.apk 
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
